### ISSUE TITLE
[Feature] Include a file in a Todo

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#4]
**Is your feature request related to a problem? Please describe.**
It would be nice if we had the option to add a file in each todo

**Describe the solution you'd like**

- [x] Create a class to hold information about a file(Path, Size)

- [x] Add a property in the `Todo` class to map the file

- [x] Create actions to upload and view the file

- [x] Last but not least, front-end additions to expose the above actions

**Additional context**
Documentation: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0
